config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  resources :users
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  attachment :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image
  has_many :articles,  dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    @article.save
    # @article.create
    # @article = Article.create(article_params)
    redirect_to @article
  end
  
  def edit
    @article = Article.find(params[:id])
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :image)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end


  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="container py-5 h-100">
  <div class="row">
    <div class="col-md-6 mx-auto">
      <%= form_with model: @article do |f| %>
      <div class="card" style="width: 40rem;">
        <%= f.label :image, '写真' %>
        <%= f.attachment_field :image, class: "card-img-top" %>

        <div class="card-body text-center mb-4">
          <h4 class="card-title">
            <%= f.text_field :title %>
          </h4>
          <p class="card-text">
            <%= f.text_area :body %>
          </p>
          <%= link_to '詳細ページ', @article, class: 'btn btn-primary' %>
        </div>

      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<h1>Articles#index</h1>
<p>Find me in app/views/articles/index.html.erb</p>

app/views/articles/new.html.erb
<h1>Articles#new</h1>
<p>Find me in app/views/articles/new.html.erb</p>

<%= form_with model: @article do |f| %>

  <%= f.label :title, 'タイトル', class: '' %>
  <%= f.text_field :title %>

  <%= f.label :body, '本文' %>
  <%= f.text_area :body %>

  <%= f.label :image, '画像' %>
  <%= f.attachment_field :image %>

  <%= f.submit '投稿' %>

<% end %>

app/views/articles/show.html.erb
<div class="container py-5 h-100">
  <div class="row">
    <div class="col-md-6 mx-auto">

      <div class="card" style="width: 40rem;">

        <%= attachment_image_tag @article, :image, class: "card-img-top" %>

        <div class="card-body text-center mb-4">
          <h4 class="card-title"><%= @article.title %></h4>
          <p class="card-text"><%= @article.body %></p>

          <% if @article.user.id == current_user.id %>
            <%= link_to '編集', edit_article_path(@article), class: 'btn btn-primary' %>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Posts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<%= stylesheet_pack_tag 'application' %>
<%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div>
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div>
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <!-- Brand -->
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1>posts</h1>
    <% end %>

    <!-- Links -->
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Poster', users_path, class: "nav-link" %>
        </li>
    <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>

    <% else %>
      <li class="nav-item">
        <%= link_to 'ログイン', new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to '新規登録', new_user_registration_path, class: "nav-link" %>
      </li>

    <% end %>
  </ul>
</nav>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

<%= form_with model: @user do |f| %>

  <%= f.label :username, 'ユーザー名' %>
  <%= f.text_field :username %>

  <%= f.label :email, 'メールアドレス' %>
  <%= f.email_field :email %>

  <%= f.label :profile, 'プロフィール' %>
  <%= f.text_area :profile %>


  <%= f.label :profile_image, 'プロフィール画像' %>
  <%= f.attachment_field :profile_image %>

  <%= f.submit '更新' %>

<% end %>

app/views/users/index.html.erb
<div class="container">
  <h3>Poster一覧</h3>
  <div class="row">
    <% @users.each do |user| %>
      <div class="col-sm-3">
        <div class="card">
          <figure class="card-img-top text-center">
            <%= link_to user do %>
              <%= attachment_image_tag user, :profile_image, size: '220x170', fallback: "no-image.png" %>
            <% end %>
          </figure>
          <div class="card-body text-center">
            <h5 class="card-title">
              <%= link_to user.username, user %>
            </h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h3>マイページ</h3>
  <div class="row">
    <div class="col-sm-2 text-center">

      <%= attachment_image_tag @user, :profile_image, size: '170x170', fallback: "no-image.png" %>


      <%= @user.username %>

      <% if @user.id == current_user.id %>
        <%= @user.email %>
        <%= link_to "編集", edit_user_path(@user) %>
      <% end %>

      <%= @user.profile %>

    </div>
  </div>
</div>